/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as FeedRouteImport } from './routes/feed'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ShelvesRouteImport } from './routes/shelves'
import { Route as StudyRouteImport } from './routes/study'
import { Route as BooksBookIdRouteImport } from './routes/books.$bookId'
import { Route as ReadBookIdRouteImport } from './routes/read.$bookId'
import { Route as ReviewsWorkIdRouteImport } from './routes/reviews.$workId'
import { Route as UUsernameRouteImport } from './routes/u.$username'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedRoute = FeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ShelvesRoute = ShelvesRouteImport.update({
  id: '/shelves',
  path: '/shelves',
  getParentRoute: () => rootRouteImport,
} as any)
const StudyRoute = StudyRouteImport.update({
  id: '/study',
  path: '/study',
  getParentRoute: () => rootRouteImport,
} as any)
const BooksBookIdRoute = BooksBookIdRouteImport.update({
  id: '/books/$bookId',
  path: '/books/$bookId',
  getParentRoute: () => rootRouteImport,
} as any)
const ReadBookIdRoute = ReadBookIdRouteImport.update({
  id: '/read/$bookId',
  path: '/read/$bookId',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsWorkIdRoute = ReviewsWorkIdRouteImport.update({
  id: '/reviews/$workId',
  path: '/reviews/$workId',
  getParentRoute: () => rootRouteImport,
} as any)
const UUsernameRoute = UUsernameRouteImport.update({
  id: '/u/$username',
  path: '/u/$username',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/feed': typeof FeedRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/shelves': typeof ShelvesRoute
  '/study': typeof StudyRoute
  '/books/$bookId': typeof BooksBookIdRoute
  '/read/$bookId': typeof ReadBookIdRoute
  '/reviews/$workId': typeof ReviewsWorkIdRoute
  '/u/$username': typeof UUsernameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/feed': typeof FeedRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/shelves': typeof ShelvesRoute
  '/study': typeof StudyRoute
  '/books/$bookId': typeof BooksBookIdRoute
  '/read/$bookId': typeof ReadBookIdRoute
  '/reviews/$workId': typeof ReviewsWorkIdRoute
  '/u/$username': typeof UUsernameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/feed': typeof FeedRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/shelves': typeof ShelvesRoute
  '/study': typeof StudyRoute
  '/books/$bookId': typeof BooksBookIdRoute
  '/read/$bookId': typeof ReadBookIdRoute
  '/reviews/$workId': typeof ReviewsWorkIdRoute
  '/u/$username': typeof UUsernameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/feed'
    | '/search'
    | '/settings'
    | '/shelves'
    | '/study'
    | '/books/$bookId'
    | '/read/$bookId'
    | '/reviews/$workId'
    | '/u/$username'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/feed'
    | '/search'
    | '/settings'
    | '/shelves'
    | '/study'
    | '/books/$bookId'
    | '/read/$bookId'
    | '/reviews/$workId'
    | '/u/$username'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/feed'
    | '/search'
    | '/settings'
    | '/shelves'
    | '/study'
    | '/books/$bookId'
    | '/read/$bookId'
    | '/reviews/$workId'
    | '/u/$username'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  FeedRoute: typeof FeedRoute
  SearchRoute: typeof SearchRoute
  SettingsRoute: typeof SettingsRoute
  ShelvesRoute: typeof ShelvesRoute
  StudyRoute: typeof StudyRoute
  BooksBookIdRoute: typeof BooksBookIdRoute
  ReadBookIdRoute: typeof ReadBookIdRoute
  ReviewsWorkIdRoute: typeof ReviewsWorkIdRoute
  UUsernameRoute: typeof UUsernameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed': {
      id: '/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof FeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shelves': {
      id: '/shelves'
      path: '/shelves'
      fullPath: '/shelves'
      preLoaderRoute: typeof ShelvesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/study': {
      id: '/study'
      path: '/study'
      fullPath: '/study'
      preLoaderRoute: typeof StudyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/books/$bookId': {
      id: '/books/$bookId'
      path: '/books/$bookId'
      fullPath: '/books/$bookId'
      preLoaderRoute: typeof BooksBookIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/read/$bookId': {
      id: '/read/$bookId'
      path: '/read/$bookId'
      fullPath: '/read/$bookId'
      preLoaderRoute: typeof ReadBookIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews/$workId': {
      id: '/reviews/$workId'
      path: '/reviews/$workId'
      fullPath: '/reviews/$workId'
      preLoaderRoute: typeof ReviewsWorkIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$username': {
      id: '/u/$username'
      path: '/u/$username'
      fullPath: '/u/$username'
      preLoaderRoute: typeof UUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  FeedRoute: FeedRoute,
  SearchRoute: SearchRoute,
  SettingsRoute: SettingsRoute,
  ShelvesRoute: ShelvesRoute,
  StudyRoute: StudyRoute,
  BooksBookIdRoute: BooksBookIdRoute,
  ReadBookIdRoute: ReadBookIdRoute,
  ReviewsWorkIdRoute: ReviewsWorkIdRoute,
  UUsernameRoute: UUsernameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
